name: Retrain Model

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: retrain_env
        environment-file: MLProject/conda.yaml
        auto-activate-base: false

    - name: Install MLflow
      run: |
        pip install mlflow

    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run . --env-manager=local

    - name: Copy artefak model ke folder simpan
      run: |
        mkdir -p saved_models
        cp MLProject/model_rf.pkl saved_models/

    - name: Commit artefak ke GitHub
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add saved_models/model_rf.pkl || true
        git diff --cached --quiet || git commit -m "Add retrained model artefact"

        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git push origin HEAD:${{ github.ref_name }}
